[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "zonectl"
version = "4.8.1"
description = "Transactional DNS Management Toolkit"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Wojciech Lipiński" }
]

[project.scripts]
zctl = "zonectl.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
